import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "sonner";

import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <header>
                        <Navbar />
                    </header>
                    <main>
                        {children}
                        <Toaster richColors  visibleToasts={1} />
                    </main>
                </body>
            </html>
        </ClerkProvider>
    );
}
