import type { Metadata } from "next";
import Navbar from "@/components/Dashboard/Navbar/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex h-screen w-full">
                <Navbar />
                {children}
            </body>
        </html>
    );
}
